[workspace]
members = [
    "crates/storage",
    "crates/execution",
    "crates/sql",
    "crates/cli",
    "crates/utils",
    "crates/table",
]
resolver = "3"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
