[workspace]
members = [
    "crates/core",
    "crates/database",
    "crates/sql",

    "crates/storage",

    "crates/cli", 

    "tests"
]
resolver = "3"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
